name = "poemonger-web"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-10"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

kv_namespaces = [
  { binding = "USERS_KV", id = "ec2910a743624059bcdb7b0ab67710c7" },
  { binding = "USERS_SESSIONS", id = "bad74c3118c841179e7419dd8afba71f" }
]

[env.preview]
kv_namespaces = [
  { binding = "USERS_KV", id = "88b79b5380e24a6e8cd9d29080556a0d" },
  { binding = "USERS_SESSIONS", id = "3a37eaaa99564c3db294b7e9bc721086" }
]

[env.production]
kv_namespaces = [
  { binding = "USERS_KV", id = "6d2850c6f82845fb999681e01a251f99" },
  { binding = "USERS_SESSIONS", id = "d827aa390bc14c969ec72fc06af62ff7" }
]
