name = "poemonger-web"
compatibility_flags = [ "nodejs_compat"  ]

[dev]
port = 8787

[[kv_namespaces]]
binding = "USERS_KV"
id = "ec2910a743624059bcdb7b0ab67710c7"

[[env.preview.kv_namespaces]]
binding = "USERS_KV"
id = "88b79b5380e24a6e8cd9d29080556a0d"

[[env.production.kv_namespaces]]
binding = "USERS_KV"
id = "6d2850c6f82845fb999681e01a251f99"