name = "poemonger-web"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-10"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[[kv_namespaces]]
binding = "USERS_KV"
id = "ec2910a743624059bcdb7b0ab67710c7"

[[env.preview.kv_namespaces]]
binding = "USERS_KV"
id = "88b79b5380e24a6e8cd9d29080556a0d"

[[env.production.kv_namespaces]]
binding = "USERS_KV"
id = "6d2850c6f82845fb999681e01a251f99"

[[durable_objects.bindings]]
name = "POEMONGER_SESSIONS"
class_name = "PoemongerSessions"

[[env.preview.durable_objects.bindings]]
name = "POEMONGER_SESSIONS"
class_name = "PoemongerSessions"

[[env.production.durable_objects.bindings]]
name = "POEMONGER_SESSIONS"
class_name = "PoemongerSessions"

[[migrations]]
migrations = [{ tag = "v1", new_classes = ["PoemongerSessions"] }]

[[env.preview.migrations]]
migrations = [{ tag = "v1", new_classes = ["PoemongerSessions"] }]

[[env.production.migrations]]
migrations = [{ tag = "v1", new_classes = ["PoemongerSessions"] }]
